[package]
name = "forfun-os"
version = "0.1.0"
edition = "2021"

[dependencies]
sbi-rt = { version = "0.0.3", features = ["legacy"] }
log = "0.4"
riscv = "0.10.1"
once_cell = { version = "1.19.0", features = ["alloc"] }
buddy_system_allocator = "0.6"
